//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/A3/TappyPlane.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TappyPlane : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TappyPlane()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TappyPlane"",
    ""maps"": [
        {
            ""name"": ""PlaneController"",
            ""id"": ""c0447d3c-ae59-4791-b532-ae3c3907f374"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""1564e8e2-d743-41b3-80f2-9605d54a76ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ecd2fb15-970f-49ef-a5da-c7fbb99932f8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlaneController
        m_PlaneController = asset.FindActionMap("PlaneController", throwIfNotFound: true);
        m_PlaneController_Jump = m_PlaneController.FindAction("Jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlaneController
    private readonly InputActionMap m_PlaneController;
    private IPlaneControllerActions m_PlaneControllerActionsCallbackInterface;
    private readonly InputAction m_PlaneController_Jump;
    public struct PlaneControllerActions
    {
        private @TappyPlane m_Wrapper;
        public PlaneControllerActions(@TappyPlane wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_PlaneController_Jump;
        public InputActionMap Get() { return m_Wrapper.m_PlaneController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlaneControllerActions set) { return set.Get(); }
        public void SetCallbacks(IPlaneControllerActions instance)
        {
            if (m_Wrapper.m_PlaneControllerActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_PlaneControllerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlaneControllerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlaneControllerActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_PlaneControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public PlaneControllerActions @PlaneController => new PlaneControllerActions(this);
    public interface IPlaneControllerActions
    {
        void OnJump(InputAction.CallbackContext context);
    }
}
